name: datahub-2017-fall

dependencies:
  - python=3.6
  - notebook=5.1.0
  - ipywidgets=6.0.0
  - jupyterlab=0.26.5
  - matplotlib=2.0.0
  - numpy=1.12.1
  - pandas=0.19.2
  - scipy=0.19.1
  - statsmodels=0.8.0
  - pip:
    - datascience=0.10.3
    - git+https://github.com/jupyterhub/jupyterhub@0.8.0rc2
    - okpy=1.12.5
    - nbgitpuller=0.3
